### PR TITLE
Fix nit in ConfigDataSelector

### PR DESCRIPTION
**Pull request by pmorie**
Fixing one last nit, @tmrts PTAL

### CODE REVIEW

**Comment by tmrts** [comment]
Shouldn't `ConfigDataName` field just be `Name`? Having that prefix seems redundant

**Comment by pmorie** [comment]
@tmrts, @bgrant0607 pointed out that we should follow the pattern in `SecretVolumeSource`.  We also try to avoid fields with the name "Name" except for the `ObjectMeta` field.

**Comment by tmrts** [comment]
Understood LGTM

**Comment by bgrant0607** [comment]
LGTM, thanks.

**Pull request merged**
